# Generated by Django 2.1.5 on 2019-02-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_salary', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_acronym', models.CharField(max_length=10)),
                ('dep_name', models.CharField(max_length=50)),
                ('dep_address', models.CharField(blank=True, max_length=50)),
                ('dep_email', models.EmailField(blank=True, max_length=50)),
                ('dep_phone', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.IntegerField(auto_created=True)),
                ('doc_name', models.CharField(max_length=20)),
                ('doc_date', models.DateField(auto_now_add=True)),
                ('doc_file', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=20)),
                ('civil_status', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('degree', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('birth', models.DateTimeField(blank=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Category')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
