# Generated by Django 2.1.5 on 2019-02-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cod',
            field=models.IntegerField(),
        ),
    ]
