# Generated by Django 2.1.5 on 2019-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190211_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
