# Generated by Django 2.1.5 on 2019-02-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default='CED', on_delete=django.db.models.deletion.CASCADE, to='employees.Department'),
        ),
    ]
